# Generated by Django 5.1.6 on 2025-02-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOpsTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('updated_value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdatableTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(blank=True, default='', max_length=100)),
                ('field2', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
