# Generated by Django 5.1.7 on 2025-04-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_test_db', '0002_customer_product_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('PN', 'Pending Status'), ('PR', 'Processing'), ('CP', 'Completed'), ('CN', 'Cancelled')], default='PN'),
        ),
    ]
